### ISSUE TITLE
Add medication

### ISSUE THREAD

**Issue by rrabinovitch** [gabichuelas/mset_app#13]
As an authenticated user,
When I click the <add medications "Here"> button,
I am redirected to a page with a text field to search medications by name.

When I search for "adderall",
A maximum of 10 search results are displayed,
And I can select the specific medication I'd like to add to my medication list by clicking "Save medication."

**Scenarios:**
- [ ] If I'd like to add a second medication to my list after adding "adderall," I can click "Save medication and add another" which renders a blank search field for me to search for the next medication.
- [ ] If I don't want to add any more medications, I click "Save medications list" and am redirected to a medications index page, where I see my list of medications (#20)

**Implementation details:**
- [x] When a medication is successfully added to my list, a flash message appears to confirm the successful action
- [x] create `UserMedications` and `MedicationSymptoms` tables
- [x] when a medication is added to the list, its name and product ndc # are saved in the db _and_ that medication's side effects list is also saved
- [x] the product ndc # is then used to search for and save the medication's side effects list
- [x] as a medication is saved, the potential side effects list is also saved in the `MedicationSymptoms` table:`https://api.fda.gov/drug/label.json?search=openfda.product_ndc.exact:"<product-ndc>"` - _this is what then populates the list of side effects a user may choose from in the symptom logging form_
- [ ] implement VCR for testing

**Comment by rrabinovitch** [comment]
this endpoint might be better for searching by name in order to access product ndc: https://api.fda.gov/drug/ndc.json?search=brand_name_base:%22adderall%22&limit=10

**Comment by gabichuelas** [comment]
In this user story, it's asking for the ability to save one medication and then choose to add another first rather than just be redirected to the user dashboard. 

The way the code is written now, each medication search result is an actual button. Clicking the button adds the medication to your list (and associated symptoms) and redirects to the dashboard. I propose we leave it like this for now, and if we have time later we can change this to be a radio button selection and then the user can either `Save` or `Save and Add Another`.

@ejdelsztejn @rrabinovitch @michaeljevans

**Comment by gabichuelas** [comment]
I'm opening another ticket for VCR implementation and moving this one over to review.
